"""SkillHub initial production schema.

Revision ID: 0001_initial_schema
Revises:
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '0001_initial_schema'
down_revision = None
branch_labels = None
depends_on = None


def _seed_publish_targets() -> None:
    targets = sa.table(
        'publish_targets',
        sa.column('id', sa.Text()),
        sa.column('target_key', sa.Text()),
        sa.column('name', sa.Text()),
        sa.column('description', sa.Text()),
        sa.column('enabled', sa.Boolean()),
        sa.column('auto_publish_enabled', sa.Boolean()),
        sa.column('gate_expression', postgresql.JSONB()),
        sa.column('config', postgresql.JSONB()),
        sa.column('created_by', sa.Text()),
    )
    default_gate = {
        'type': 'group',
        'op': 'and',
        'children': [
            {'type': 'check', 'check_id': 'min_responses', 'params': {'min': 1}},
            {'type': 'check', 'check_id': 'no_negative_score', 'params': {}},
        ],
    }
    op.bulk_insert(
        targets,
        [
            {
                'id': target_id,
                'target_key': key,
                'name': name,
                'description': description,
                'enabled': True,
                'auto_publish_enabled': False,
                'gate_expression': default_gate,
                'config': {},
                'created_by': 'system',
            }
            for target_id, key, name, description in (
                ('target_yunxi', 'yunxi', '云析', '云析发布源'),
                ('target_agentcenter', 'agentcenter', 'AgentCenter', 'AgentCenter 发布源'),
                ('target_custom1', 'custom1', '自定义1', '预留自定义发布源 1'),
                ('target_custom2', 'custom2', '自定义2', '预留自定义发布源 2'),
            )
        ],
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('namespace', sa.Text(), nullable=False),
    sa.Column('locator', sa.Text(), nullable=False),
    sa.Column('digest', sa.Text(), nullable=False),
    sa.Column('media_type', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('size_bytes >= 0', name='artifacts_size_bytes_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('locator', 'digest', name='artifacts_locator_digest_unique')
    )
    op.create_index('artifacts_namespace_idx', 'artifacts', ['namespace'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('actor_ref', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.Text(), nullable=False),
    sa.Column('resource_id', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('audit_events_resource_idx', 'audit_events', ['resource_type', 'resource_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('scope_type', sa.Text(), server_default=sa.text("'global'"), nullable=False),
    sa.Column('scope_id', sa.Text(), server_default=sa.text("'default'"), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("scope_type in ('global', 'skill')", name='groups_scope_type_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_type', 'scope_id', 'name', name='groups_scope_name_unique')
    )
    op.create_index('groups_scope_idx', 'groups', ['scope_type', 'scope_id', 'name'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_ref', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('locked_by', sa.Text(), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('queued', 'running', 'succeeded', 'failed', 'canceled')", name='jobs_status_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('jobs_status_created_at_idx', 'jobs', ['status', 'created_at'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('recipient_actor_id', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('resource_type', sa.Text(), nullable=False),
    sa.Column('resource_id', sa.Text(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('notifications_recipient_idx', 'notifications', ['recipient_actor_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('opencode_agents',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('permission', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('provider_id', sa.Text(), nullable=True),
    sa.Column('model_id', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Text(), nullable=True),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("id ~ '^[A-Za-z0-9_-]+$'", name='opencode_agents_id_format_check'),
    sa.CheckConstraint("jsonb_typeof(permission) = 'object'", name='opencode_agents_permission_object'),
    sa.CheckConstraint("jsonb_typeof(steps) = 'array'", name='opencode_agents_steps_array'),
    sa.CheckConstraint('length(btrim(name)) > 0', name='opencode_agents_name_non_empty'),
    sa.CheckConstraint('length(btrim(prompt)) > 0', name='opencode_agents_prompt_non_empty'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('opencode_agents_enabled_idx', 'opencode_agents', ['enabled', 'deleted_at', 'name'], unique=False)
    op.create_table('publish_targets',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('target_key', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('auto_publish_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('gate_expression', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(config) = 'object'", name='publish_targets_config_object'),
    sa.CheckConstraint("jsonb_typeof(gate_expression) = 'object'", name='publish_targets_gate_expression_object'),
    sa.CheckConstraint('length(btrim(target_key)) > 0', name='publish_targets_key_non_empty'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_key', name='publish_targets_key_unique')
    )
    op.create_index('publish_targets_enabled_idx', 'publish_targets', ['enabled', 'target_key'], unique=False)
    op.create_table('role_assignments',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('subject_type', sa.Text(), nullable=False),
    sa.Column('subject_id', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.Text(), nullable=False),
    sa.Column('resource_id', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("resource_type in ('skill', 'skill_tag')", name='role_assignments_resource_type_check'),
    sa.CheckConstraint("role in ('admin', 'owner', 'maintainer', 'evaluator', 'reviewer', 'viewer')", name='role_assignments_role_check'),
    sa.CheckConstraint("subject_type in ('user', 'group')", name='role_assignments_subject_type_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_type', 'subject_id', 'resource_type', 'resource_id', 'role', name='role_assignments_scope_unique')
    )
    op.create_index('role_assignments_resource_idx', 'role_assignments', ['resource_type', 'resource_id'], unique=False)
    op.create_index('role_assignments_subject_idx', 'role_assignments', ['subject_type', 'subject_id'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('owner_ref', sa.Text(), nullable=False),
    sa.Column('current_version_id', sa.Text(), nullable=True),
    sa.Column('lifecycle_status', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("lifecycle_status in ('active', 'archived')", name='skills_lifecycle_status_check'),
    sa.ForeignKeyConstraint(['current_version_id', 'id'], ['skill_versions.id', 'skill_versions.skill_id'], name='skills_current_version_fkey', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='skills_slug_unique')
    )
    op.create_table('tag_groups',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('required', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('free_form', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("id ~ '^[A-Za-z0-9_-]+$'", name='tag_groups_id_format_check'),
    sa.CheckConstraint('length(btrim(display_name)) > 0', name='tag_groups_display_name_non_empty'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('tag_groups_sort_idx', 'tag_groups', ['sort_order', 'id'], unique=False)
    op.create_table('worker_heartbeats',
    sa.Column('worker_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'idle'"), nullable=False),
    sa.Column('current_job_id', sa.Text(), nullable=True),
    sa.Column('current_job_type', sa.Text(), nullable=True),
    sa.Column('current_run_id', sa.Text(), nullable=True),
    sa.Column('current_session_id', sa.Text(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint("status in ('idle', 'running')", name='worker_heartbeats_status_check'),
    sa.PrimaryKeyConstraint('worker_id')
    )
    op.create_index('worker_heartbeats_last_seen_idx', 'worker_heartbeats', [sa.literal_column('last_seen_at DESC')], unique=False)
    op.create_table('workflow_collection_definitions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('latest_revision', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('latest_revision > 0', name='workflow_collection_definitions_revision_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eval_cases',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('skill_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('current_version_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_version_id', 'skill_id'], ['eval_case_versions.id', 'eval_case_versions.skill_id'], name='eval_cases_current_version_fkey', use_alter=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'skill_id', name='eval_cases_id_skill_unique')
    )
    op.create_index('eval_cases_skill_id_idx', 'eval_cases', ['skill_id'], unique=False)
    op.create_table('eval_sets',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('skill_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'skill_id', name='eval_sets_id_skill_unique'),
    sa.UniqueConstraint('skill_id', 'name', name='eval_sets_skill_name_unique')
    )
    op.create_index('eval_sets_skill_id_idx', 'eval_sets', ['skill_id'], unique=False)
    op.create_table('group_memberships',
    sa.Column('group_id', sa.Text(), nullable=False),
    sa.Column('subject_type', sa.Text(), nullable=False),
    sa.Column('subject_id', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("subject_type in ('user')", name='group_memberships_subject_type_check'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'subject_type', 'subject_id')
    )
    op.create_index('group_memberships_subject_idx', 'group_memberships', ['subject_type', 'subject_id'], unique=False)
    op.create_table('saved_views',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('skill_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('view_type', sa.Text(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("view_type in ('run_history')", name='saved_views_type_check'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_id', 'view_type', 'name', name='saved_views_skill_type_name_unique')
    )
    op.create_index('saved_views_skill_type_idx', 'saved_views', ['skill_id', 'view_type'], unique=False)
    op.create_table('skill_versions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('skill_id', sa.Text(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('content_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_digest', sa.Text(), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("version ~ '^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-([0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*))?(?:\\+([0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*))?$'", name='skill_versions_version_semver_check'),
    sa.CheckConstraint('version_number > 0', name='skill_versions_version_number_positive'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'skill_id', name='skill_versions_id_skill_unique'),
    sa.UniqueConstraint('skill_id', 'version', name='skill_versions_skill_semver_unique'),
    sa.UniqueConstraint('skill_id', 'version_number', name='skill_versions_skill_version_unique')
    )
    op.create_index('skill_versions_skill_id_idx', 'skill_versions', ['skill_id'], unique=False)
    op.create_table('tag_values',
    sa.Column('tag_group_id', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(btrim(value)) > 0', name='tag_values_value_non_empty'),
    sa.ForeignKeyConstraint(['tag_group_id'], ['tag_groups.id'], ),
    sa.PrimaryKeyConstraint('tag_group_id', 'value')
    )
    op.create_index('tag_values_group_sort_idx', 'tag_values', ['tag_group_id', 'sort_order', 'value'], unique=False)
    op.create_table('workflow_collection_revisions',
    sa.Column('definition_id', sa.Text(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('document_schema_version', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('definition_digest', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(definition) = 'object'", name='workflow_collection_revisions_definition_object'),
    sa.CheckConstraint('document_schema_version > 0', name='workflow_collection_revisions_schema_version_positive'),
    sa.CheckConstraint('revision > 0', name='workflow_collection_revisions_revision_positive'),
    sa.ForeignKeyConstraint(['definition_id'], ['workflow_collection_definitions.id'], ),
    sa.PrimaryKeyConstraint('definition_id', 'revision')
    )
    op.create_index('workflow_collection_revisions_created_at_idx', 'workflow_collection_revisions', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('skill_id', sa.Text(), nullable=False),
    sa.Column('revision', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('document_schema_version', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('document', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('document_digest', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('last_saved_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(document) = 'object'", name='workflows_document_object'),
    sa.CheckConstraint('document_schema_version > 0', name='workflows_schema_version_positive'),
    sa.CheckConstraint('revision > 0', name='workflows_revision_positive'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_id', name='workflows_skill_unique')
    )
    op.create_index('workflows_updated_at_idx', 'workflows', [sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('eval_case_versions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('skill_id', sa.Text(), nullable=False),
    sa.Column('case_id', sa.Text(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('workspace_artifact_id', sa.Text(), nullable=True),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('runner_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(runner_config) = 'object'", name='eval_case_versions_runner_config_object'),
    sa.CheckConstraint("jsonb_typeof(steps) = 'array'", name='eval_case_versions_steps_array'),
    sa.CheckConstraint('version_number > 0', name='eval_case_versions_version_number_positive'),
    sa.ForeignKeyConstraint(['case_id', 'skill_id'], ['eval_cases.id', 'eval_cases.skill_id'], name='eval_case_versions_case_skill_fkey'),
    sa.ForeignKeyConstraint(['workspace_artifact_id'], ['artifacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'version_number', name='eval_case_versions_case_version_unique'),
    sa.UniqueConstraint('id', 'skill_id', name='eval_case_versions_id_skill_unique')
    )
    op.create_index('eval_case_versions_case_id_idx', 'eval_case_versions', ['case_id'], unique=False)
    op.create_index('eval_case_versions_skill_id_idx', 'eval_case_versions', ['skill_id'], unique=False)
    op.create_table('eval_runs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('skill_id', sa.Text(), nullable=False),
    sa.Column('skill_version_id', sa.Text(), nullable=False),
    sa.Column('eval_set_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('environment_tags', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('run_context', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('run_context_hash', sa.Text(), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('result_artifact_id', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('queued', 'running', 'finished', 'failed')", name='eval_runs_status_check'),
    sa.ForeignKeyConstraint(['eval_set_id', 'skill_id'], ['eval_sets.id', 'eval_sets.skill_id'], name='eval_runs_eval_set_skill_fkey'),
    sa.ForeignKeyConstraint(['result_artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['skill_version_id', 'skill_id'], ['skill_versions.id', 'skill_versions.skill_id'], name='eval_runs_skill_version_skill_fkey'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'skill_id', name='eval_runs_id_skill_unique')
    )
    op.create_index('eval_runs_context_hash_idx', 'eval_runs', ['run_context_hash'], unique=False)
    op.create_index('eval_runs_eval_set_id_idx', 'eval_runs', ['eval_set_id'], unique=False)
    op.create_index('eval_runs_skill_id_created_at_idx', 'eval_runs', ['skill_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('eval_runs_skill_version_id_idx', 'eval_runs', ['skill_version_id'], unique=False)
    op.create_table('eval_set_cases',
    sa.Column('eval_set_id', sa.Text(), nullable=False),
    sa.Column('skill_id', sa.Text(), nullable=False),
    sa.Column('case_id', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.CheckConstraint('position >= 0', name='eval_set_cases_position_non_negative'),
    sa.ForeignKeyConstraint(['case_id', 'skill_id'], ['eval_cases.id', 'eval_cases.skill_id'], name='eval_set_cases_case_skill_fkey'),
    sa.ForeignKeyConstraint(['eval_set_id', 'skill_id'], ['eval_sets.id', 'eval_sets.skill_id'], name='eval_set_cases_set_skill_fkey'),
    sa.PrimaryKeyConstraint('eval_set_id', 'position'),
    sa.UniqueConstraint('eval_set_id', 'case_id', name='eval_set_cases_case_unique')
    )
    op.create_index('eval_set_cases_case_id_idx', 'eval_set_cases', ['case_id'], unique=False)
    op.create_index('eval_set_cases_skill_id_idx', 'eval_set_cases', ['skill_id'], unique=False)
    op.create_table('review_requests',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('skill_id', sa.Text(), nullable=False),
    sa.Column('skill_version_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('open', 'closed', 'cancelled')", name='review_requests_status_check'),
    sa.ForeignKeyConstraint(['skill_version_id', 'skill_id'], ['skill_versions.id', 'skill_versions.skill_id'], name='review_requests_skill_version_skill_fkey'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'skill_id', name='review_requests_id_skill_unique')
    )
    op.create_index('review_requests_skill_version_idx', 'review_requests', ['skill_version_id'], unique=False)
    op.create_table('skill_builder_sessions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('actor_ref', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('opencode_session_id', sa.Text(), nullable=True),
    sa.Column('workdir', sa.Text(), nullable=True),
    sa.Column('draft_files', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('run_selection', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_skill_id', sa.Text(), nullable=True),
    sa.Column('created_skill_version_id', sa.Text(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(draft_files) = 'array'", name='skill_builder_sessions_draft_files_array'),
    sa.CheckConstraint("jsonb_typeof(run_selection) = 'object'", name='skill_builder_sessions_run_selection_object'),
    sa.CheckConstraint("status in ('active', 'running', 'draft_ready', 'created', 'failed')", name='skill_builder_sessions_status_check'),
    sa.ForeignKeyConstraint(['created_skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['created_skill_version_id'], ['skill_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('skill_builder_sessions_actor_idx', 'skill_builder_sessions', ['actor_ref', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('skill_builder_sessions_status_idx', 'skill_builder_sessions', ['status', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('skill_tags',
    sa.Column('skill_id', sa.Text(), nullable=False),
    sa.Column('tag_group_id', sa.Text(), nullable=False),
    sa.Column('tag_value', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['tag_group_id', 'tag_value'], ['tag_values.tag_group_id', 'tag_values.value'], name='skill_tags_tag_value_fkey'),
    sa.PrimaryKeyConstraint('skill_id', 'tag_group_id', 'tag_value')
    )
    op.create_index('skill_tags_group_value_idx', 'skill_tags', ['tag_group_id', 'tag_value'], unique=False)
    op.create_table('tag_group_cascades',
    sa.Column('child_tag_group_id', sa.Text(), nullable=False),
    sa.Column('parent_tag_group_id', sa.Text(), nullable=False),
    sa.Column('parent_tag_value', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('child_tag_group_id <> parent_tag_group_id', name='tag_group_cascades_no_self_parent_check'),
    sa.ForeignKeyConstraint(['child_tag_group_id'], ['tag_groups.id'], ),
    sa.ForeignKeyConstraint(['parent_tag_group_id', 'parent_tag_value'], ['tag_values.tag_group_id', 'tag_values.value'], name='tag_group_cascades_parent_value_fkey'),
    sa.PrimaryKeyConstraint('child_tag_group_id')
    )
    op.create_index('tag_group_cascades_parent_idx', 'tag_group_cascades', ['parent_tag_group_id', 'parent_tag_value'], unique=False)
    op.create_table('workflow_syncs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('workflow_id', sa.Text(), nullable=False),
    sa.Column('workflow_revision', sa.Integer(), nullable=False),
    sa.Column('document_schema_version', sa.Integer(), nullable=False),
    sa.Column('source_artifact_id', sa.Text(), nullable=False),
    sa.Column('skill_version_id', sa.Text(), nullable=False),
    sa.Column('generator_version', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('document_schema_version > 0', name='workflow_syncs_schema_version_positive'),
    sa.CheckConstraint('workflow_revision > 0', name='workflow_syncs_revision_positive'),
    sa.ForeignKeyConstraint(['skill_version_id'], ['skill_versions.id'], ),
    sa.ForeignKeyConstraint(['source_artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_version_id', name='workflow_syncs_skill_version_unique'),
    sa.UniqueConstraint('workflow_id', 'workflow_revision', name='workflow_syncs_workflow_revision_unique')
    )
    op.create_index('workflow_syncs_skill_version_idx', 'workflow_syncs', ['skill_version_id'], unique=False)
    op.create_table('accepted_verifications',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('skill_id', sa.Text(), nullable=False),
    sa.Column('skill_version_id', sa.Text(), nullable=False),
    sa.Column('eval_set_id', sa.Text(), nullable=False),
    sa.Column('run_context_hash', sa.Text(), nullable=False),
    sa.Column('eval_run_id', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['eval_run_id', 'skill_id'], ['eval_runs.id', 'eval_runs.skill_id'], name='accepted_verifications_eval_run_skill_fkey'),
    sa.ForeignKeyConstraint(['eval_set_id', 'skill_id'], ['eval_sets.id', 'eval_sets.skill_id'], name='accepted_verifications_eval_set_skill_fkey'),
    sa.ForeignKeyConstraint(['skill_version_id', 'skill_id'], ['skill_versions.id', 'skill_versions.skill_id'], name='accepted_verifications_skill_version_skill_fkey'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'skill_id', name='accepted_verifications_id_skill_unique'),
    sa.UniqueConstraint('skill_id', 'skill_version_id', 'eval_set_id', 'run_context_hash', name='accepted_verifications_context_unique')
    )
    op.create_index('accepted_verifications_context_idx', 'accepted_verifications', ['skill_id', 'skill_version_id', 'eval_set_id', 'run_context_hash'], unique=False)
    op.create_index('accepted_verifications_eval_run_id_idx', 'accepted_verifications', ['eval_run_id'], unique=False)
    op.create_table('case_results',
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('skill_id', sa.Text(), nullable=False),
    sa.Column('case_version_id', sa.Text(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('result_artifact_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score in (0, 1)', name='case_results_score_pass_fail'),
    sa.ForeignKeyConstraint(['case_version_id', 'skill_id'], ['eval_case_versions.id', 'eval_case_versions.skill_id'], name='case_results_case_skill_fkey'),
    sa.ForeignKeyConstraint(['result_artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['run_id', 'skill_id'], ['eval_runs.id', 'eval_runs.skill_id'], name='case_results_run_skill_fkey'),
    sa.PrimaryKeyConstraint('run_id', 'case_version_id')
    )
    op.create_index('case_results_case_version_id_idx', 'case_results', ['case_version_id'], unique=False)
    op.create_index('case_results_skill_id_idx', 'case_results', ['skill_id'], unique=False)
    op.create_table('eval_case_runs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('job_id', sa.Text(), nullable=True),
    sa.Column('skill_id', sa.Text(), nullable=False),
    sa.Column('skill_version_id', sa.Text(), nullable=False),
    sa.Column('eval_set_id', sa.Text(), nullable=False),
    sa.Column('case_version_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('environment_tags', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('run_context', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('run_context_hash', sa.Text(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('result_artifact_id', sa.Text(), nullable=True),
    sa.Column('runner_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('queued', 'running', 'succeeded', 'failed', 'canceled')", name='eval_case_runs_status_check'),
    sa.CheckConstraint('score is null or score in (0, 1)', name='eval_case_runs_score_pass_fail'),
    sa.ForeignKeyConstraint(['case_version_id', 'skill_id'], ['eval_case_versions.id', 'eval_case_versions.skill_id'], name='eval_case_runs_case_skill_fkey'),
    sa.ForeignKeyConstraint(['eval_set_id', 'skill_id'], ['eval_sets.id', 'eval_sets.skill_id'], name='eval_case_runs_eval_set_skill_fkey'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['result_artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['skill_version_id', 'skill_id'], ['skill_versions.id', 'skill_versions.skill_id'], name='eval_case_runs_skill_version_skill_fkey'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'skill_id', name='eval_case_runs_id_skill_unique')
    )
    op.create_index('eval_case_runs_case_version_id_idx', 'eval_case_runs', ['case_version_id'], unique=False)
    op.create_index('eval_case_runs_context_hash_idx', 'eval_case_runs', ['run_context_hash'], unique=False)
    op.create_index('eval_case_runs_eval_set_id_idx', 'eval_case_runs', ['eval_set_id'], unique=False)
    op.create_index('eval_case_runs_job_id_idx', 'eval_case_runs', ['job_id'], unique=False)
    op.create_index('eval_case_runs_skill_id_created_at_idx', 'eval_case_runs', ['skill_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('eval_case_runs_skill_version_id_idx', 'eval_case_runs', ['skill_version_id'], unique=False)
    op.create_table('publish_records',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('skill_id', sa.Text(), nullable=False),
    sa.Column('skill_version_id', sa.Text(), nullable=False),
    sa.Column('review_request_id', sa.Text(), nullable=False),
    sa.Column('publish_target_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('check_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('pending_confirmation', 'queued', 'releasing', 'released', 'cancelled', 'failed')", name='publish_records_status_check'),
    sa.ForeignKeyConstraint(['publish_target_id'], ['publish_targets.id'], ),
    sa.ForeignKeyConstraint(['review_request_id', 'skill_id'], ['review_requests.id', 'review_requests.skill_id'], name='publish_records_review_skill_fkey'),
    sa.ForeignKeyConstraint(['skill_version_id', 'skill_id'], ['skill_versions.id', 'skill_versions.skill_id'], name='publish_records_skill_version_skill_fkey'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'skill_id', name='publish_records_id_skill_unique'),
    sa.UniqueConstraint('skill_version_id', 'publish_target_id', name='publish_records_version_target_unique')
    )
    op.create_index('publish_records_skill_version_idx', 'publish_records', ['skill_version_id'], unique=False)
    op.create_index('publish_records_target_status_idx', 'publish_records', ['publish_target_id', 'status'], unique=False)
    op.create_table('review_check_results',
    sa.Column('review_request_id', sa.Text(), nullable=False),
    sa.Column('skill_id', sa.Text(), nullable=False),
    sa.Column('check_id', sa.Text(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_request_id', 'skill_id'], ['review_requests.id', 'review_requests.skill_id'], name='review_check_results_review_skill_fkey'),
    sa.PrimaryKeyConstraint('review_request_id', 'check_id')
    )
    op.create_index('review_check_results_check_idx', 'review_check_results', ['check_id'], unique=False)
    op.create_table('review_request_publish_targets',
    sa.Column('review_request_id', sa.Text(), nullable=False),
    sa.Column('skill_id', sa.Text(), nullable=False),
    sa.Column('publish_target_id', sa.Text(), nullable=False),
    sa.Column('auto_submit_on_pass', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['publish_target_id'], ['publish_targets.id'], ),
    sa.ForeignKeyConstraint(['review_request_id', 'skill_id'], ['review_requests.id', 'review_requests.skill_id'], name='review_request_publish_targets_review_skill_fkey'),
    sa.PrimaryKeyConstraint('review_request_id', 'publish_target_id')
    )
    op.create_index('review_request_publish_targets_target_idx', 'review_request_publish_targets', ['publish_target_id'], unique=False)
    op.create_table('review_request_reviewers',
    sa.Column('review_request_id', sa.Text(), nullable=False),
    sa.Column('skill_id', sa.Text(), nullable=False),
    sa.Column('reviewer_actor', sa.Text(), nullable=False),
    sa.Column('source_subject_type', sa.Text(), nullable=False),
    sa.Column('source_subject_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_subject_type in ('user', 'group')", name='review_request_reviewers_source_type_check'),
    sa.ForeignKeyConstraint(['review_request_id', 'skill_id'], ['review_requests.id', 'review_requests.skill_id'], name='review_request_reviewers_review_skill_fkey'),
    sa.PrimaryKeyConstraint('review_request_id', 'reviewer_actor')
    )
    op.create_index('review_request_reviewers_actor_idx', 'review_request_reviewers', ['reviewer_actor'], unique=False)
    op.create_table('skill_builder_messages',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('intent', sa.Text(), server_default=sa.text("'chat'"), nullable=False),
    sa.Column('content', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('job_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("intent in ('chat', 'generate_draft')", name='skill_builder_messages_intent_check'),
    sa.CheckConstraint("jsonb_typeof(metadata) = 'object'", name='skill_builder_messages_metadata_object'),
    sa.CheckConstraint("role in ('user', 'assistant', 'system')", name='skill_builder_messages_role_check'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['skill_builder_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('skill_builder_messages_job_id_idx', 'skill_builder_messages', ['job_id'], unique=False)
    op.create_index('skill_builder_messages_session_idx', 'skill_builder_messages', ['session_id', 'created_at'], unique=False)
    op.create_table('review_responses',
    sa.Column('review_request_id', sa.Text(), nullable=False),
    sa.Column('skill_id', sa.Text(), nullable=False),
    sa.Column('reviewer_actor', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score in (-1, 0, 1)', name='review_responses_score_check'),
    sa.ForeignKeyConstraint(['review_request_id', 'reviewer_actor'], ['review_request_reviewers.review_request_id', 'review_request_reviewers.reviewer_actor'], name='review_responses_reviewer_fkey'),
    sa.ForeignKeyConstraint(['review_request_id', 'skill_id'], ['review_requests.id', 'review_requests.skill_id'], name='review_responses_review_skill_fkey'),
    sa.PrimaryKeyConstraint('review_request_id', 'reviewer_actor')
    )
    op.create_index('review_responses_reviewer_idx', 'review_responses', ['reviewer_actor'], unique=False)
    op.create_foreign_key(
        'skills_current_version_fkey',
        'skills',
        'skill_versions',
        ['current_version_id', 'id'],
        ['id', 'skill_id'],
    )
    op.create_foreign_key(
        'eval_cases_current_version_fkey',
        'eval_cases',
        'eval_case_versions',
        ['current_version_id', 'skill_id'],
        ['id', 'skill_id'],
    )
    _seed_publish_targets()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('eval_cases_current_version_fkey', 'eval_cases', type_='foreignkey')
    op.drop_constraint('skills_current_version_fkey', 'skills', type_='foreignkey')
    op.drop_index('review_responses_reviewer_idx', table_name='review_responses')
    op.drop_table('review_responses')
    op.drop_index('skill_builder_messages_session_idx', table_name='skill_builder_messages')
    op.drop_index('skill_builder_messages_job_id_idx', table_name='skill_builder_messages')
    op.drop_table('skill_builder_messages')
    op.drop_index('review_request_reviewers_actor_idx', table_name='review_request_reviewers')
    op.drop_table('review_request_reviewers')
    op.drop_index('review_request_publish_targets_target_idx', table_name='review_request_publish_targets')
    op.drop_table('review_request_publish_targets')
    op.drop_index('review_check_results_check_idx', table_name='review_check_results')
    op.drop_table('review_check_results')
    op.drop_index('publish_records_target_status_idx', table_name='publish_records')
    op.drop_index('publish_records_skill_version_idx', table_name='publish_records')
    op.drop_table('publish_records')
    op.drop_index('eval_case_runs_skill_version_id_idx', table_name='eval_case_runs')
    op.drop_index('eval_case_runs_skill_id_created_at_idx', table_name='eval_case_runs')
    op.drop_index('eval_case_runs_job_id_idx', table_name='eval_case_runs')
    op.drop_index('eval_case_runs_eval_set_id_idx', table_name='eval_case_runs')
    op.drop_index('eval_case_runs_context_hash_idx', table_name='eval_case_runs')
    op.drop_index('eval_case_runs_case_version_id_idx', table_name='eval_case_runs')
    op.drop_table('eval_case_runs')
    op.drop_index('case_results_skill_id_idx', table_name='case_results')
    op.drop_index('case_results_case_version_id_idx', table_name='case_results')
    op.drop_table('case_results')
    op.drop_index('accepted_verifications_eval_run_id_idx', table_name='accepted_verifications')
    op.drop_index('accepted_verifications_context_idx', table_name='accepted_verifications')
    op.drop_table('accepted_verifications')
    op.drop_index('workflow_syncs_skill_version_idx', table_name='workflow_syncs')
    op.drop_table('workflow_syncs')
    op.drop_index('tag_group_cascades_parent_idx', table_name='tag_group_cascades')
    op.drop_table('tag_group_cascades')
    op.drop_index('skill_tags_group_value_idx', table_name='skill_tags')
    op.drop_table('skill_tags')
    op.drop_index('skill_builder_sessions_status_idx', table_name='skill_builder_sessions')
    op.drop_index('skill_builder_sessions_actor_idx', table_name='skill_builder_sessions')
    op.drop_table('skill_builder_sessions')
    op.drop_index('review_requests_skill_version_idx', table_name='review_requests')
    op.drop_table('review_requests')
    op.drop_index('eval_set_cases_skill_id_idx', table_name='eval_set_cases')
    op.drop_index('eval_set_cases_case_id_idx', table_name='eval_set_cases')
    op.drop_table('eval_set_cases')
    op.drop_index('eval_runs_skill_version_id_idx', table_name='eval_runs')
    op.drop_index('eval_runs_skill_id_created_at_idx', table_name='eval_runs')
    op.drop_index('eval_runs_eval_set_id_idx', table_name='eval_runs')
    op.drop_index('eval_runs_context_hash_idx', table_name='eval_runs')
    op.drop_table('eval_runs')
    op.drop_index('eval_case_versions_skill_id_idx', table_name='eval_case_versions')
    op.drop_index('eval_case_versions_case_id_idx', table_name='eval_case_versions')
    op.drop_table('eval_case_versions')
    op.drop_index('workflows_updated_at_idx', table_name='workflows')
    op.drop_table('workflows')
    op.drop_index('workflow_collection_revisions_created_at_idx', table_name='workflow_collection_revisions')
    op.drop_table('workflow_collection_revisions')
    op.drop_index('tag_values_group_sort_idx', table_name='tag_values')
    op.drop_table('tag_values')
    op.drop_index('skill_versions_skill_id_idx', table_name='skill_versions')
    op.drop_table('skill_versions')
    op.drop_index('saved_views_skill_type_idx', table_name='saved_views')
    op.drop_table('saved_views')
    op.drop_index('group_memberships_subject_idx', table_name='group_memberships')
    op.drop_table('group_memberships')
    op.drop_index('eval_sets_skill_id_idx', table_name='eval_sets')
    op.drop_table('eval_sets')
    op.drop_index('eval_cases_skill_id_idx', table_name='eval_cases')
    op.drop_table('eval_cases')
    op.drop_table('workflow_collection_definitions')
    op.drop_index('worker_heartbeats_last_seen_idx', table_name='worker_heartbeats')
    op.drop_table('worker_heartbeats')
    op.drop_index('tag_groups_sort_idx', table_name='tag_groups')
    op.drop_table('tag_groups')
    op.drop_table('skills')
    op.drop_index('role_assignments_subject_idx', table_name='role_assignments')
    op.drop_index('role_assignments_resource_idx', table_name='role_assignments')
    op.drop_table('role_assignments')
    op.drop_index('publish_targets_enabled_idx', table_name='publish_targets')
    op.drop_table('publish_targets')
    op.drop_index('opencode_agents_enabled_idx', table_name='opencode_agents')
    op.drop_table('opencode_agents')
    op.drop_index('notifications_recipient_idx', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('jobs_status_created_at_idx', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('groups_scope_idx', table_name='groups')
    op.drop_table('groups')
    op.drop_index('audit_events_resource_idx', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('artifacts_namespace_idx', table_name='artifacts')
    op.drop_table('artifacts')
    # ### end Alembic commands ###
